### ISSUE TITLE
seeds

### ISSUE THREAD

**Issue by lentrup** [patdrei/cool_cucumber#64]
`URI::InvalidURIError: URI must be ascii only "https://api.spoonacular.com/recipes/convert?ingredientName=cr\u00E8me fra\u00EEche&sourceAmount=6.0&sourceUnit=servings&targetUnit=grams&apiKey=BLANKEDOUT"
/Users/leon/code/lentrup/lewagon/433_berlin/projects/cool_cucumber/db/seeds.rb:77:in `block in set_ingredients'
/Users/leon/code/lentrup/lewagon/433_berlin/projects/cool_cucumber/db/seeds.rb:76:in `each'
/Users/leon/code/lentrup/lewagon/433_berlin/projects/cool_cucumber/db/seeds.rb:76:in `set_ingredients'
/Users/leon/code/lentrup/lewagon/433_berlin/projects/cool_cucumber/db/seeds.rb:130:in `block (2 levels) in <main>'
/Users/leon/code/lentrup/lewagon/433_berlin/projects/cool_cucumber/db/seeds.rb:106:in `times'
/Users/leon/code/lentrup/lewagon/433_berlin/projects/cool_cucumber/db/seeds.rb:106:in `block in <main>'
/Users/leon/code/lentrup/lewagon/433_berlin/projects/cool_cucumber/db/seeds.rb:104:in `each'
/Users/leon/code/lentrup/lewagon/433_berlin/projects/cool_cucumber/db/seeds.rb:104:in `<main>'
/Users/leon/code/lentrup/lewagon/433_berlin/projects/cool_cucumber/bin/rails:9:in `<top (required)>'
/Users/leon/code/lentrup/lewagon/433_berlin/projects/cool_cucumber/bin/spring:15:in `<top (required)>'
./bin/rails:3:in `load'
./bin/rails:3:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
`

**Comment by lentrup** [comment]
also, your API keys are not protected, any scraper on github could steal your API keys, they should always belong in the .env file
